<?php
/**	op-unit-login:/template/register/confirm.phtml
 *
 * @created    2025-06-02
 * @license    Apache-2.0
 * @package    op-unit-login
 * @copyright  (C) 2025 Tomoaki Nagahara
 */

/* @var $form \OP\UNIT\Form */

?>
<p>Please check your input.</p>
<?php $form->Start('register') ?>
<table>
	<tr>
		<td><?php $form->Label('account') ?></td>
		<td><?php $form->Value('account') ?></td>
	</tr>
	<tr>
		<td><?php $form->Label('password') ?></td>
		<td><?php $form->Value('password') ?></td>
	</tr>
	<tr>
		<td></td>
		<td>
			<button name="button" value="back"> Back </button>
			<?php $form->Input('button',['value' => 'Register']) ?>
		</td>
	</tr>
</table>
<?php $form->Finish('register') ?>
