<?php
/**	op-unit-form:/template/register/registered.phtml
 *
 * @created    2025-06-04
 * @version    1.0
 * @package    op-unit-form
 * @author     Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright  Tomoaki Nagahara All right reserved.
 */
?>
<p class="message">Your account has been successfully registered. Please log in from the login page.</p>
<p><a href="./">Go back to the login page</a></p>
