<?php
/**	op-unit-form:/template/login/form.phtml
 *
 * @created    2025-06-04
 * @version    1.0
 * @package    op-unit-form
 * @author     Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/* @var $form    \OP\UNIT\Form */
/* @var $message string        */

?>
<p><?php echo $message ?? '' ?></p>
<?php $form->Start('login') ?>
<table>
	<?php foreach( $form->Values() as $name => $value ): ?>
	<tr>
		<td><?php $form->Label($name) ?></td>
		<td><?php $form->Input($name) ?></td>
	</tr>
	<tr>
		<td></td>
		<td><?php $form->Error($name) ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<?php $form->Finish() ?>
<?php $value ?>
<p><a href="register">Register an account</a></p>
