<?php
/**	op-unit-login:/template/login/form.phtml
 *
 * @created    2025-06-04
 * @license    Apache-2.0
 * @package    op-unit-login
 * @copyright  (C) 2025 Tomoaki Nagahara
 */

/* @var $form    \OP\IF_FORM */
/* @var $message string        */

?>
<p><?php echo $message ?? '' ?></p>
<?php $form->Start('login') ?>
<table>
	<?php foreach( $form->Values() as $name => $value ): ?>
	<tr>
		<td><?php $form->Label($name) ?></td>
		<td><?php $form->Input($name) ?></td>
	</tr>
	<tr>
		<td></td>
		<td class="error">
			<?php $form->Error($name) ?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>
<?php $form->Finish() ?>
<?php $value ?>
<p><a href="register">Register an account</a></p>
